package nl.bd.aoc.day5;

public enum Direction {
//    HORIZONTAL_LEFT, HORIZONTAL_RIGHT, VERTICAL_UP, VERTICAL_DOWN, DIAGONAL_UP_LEFT_DOWN_RIGHT, DIAGONAL_DOWN_LEFT_UP_RIGHT, DIAGONAL_UP_RIGHT_DOWN_LEFT, DIAGONAL_DOWN_RIGHT_UP_LEFT, UNKNOWN
    HORIZONTAL, VERTICAL, DIAGONAL, UNKNOWN
}
